apiVersion: v1
kind: Secret
metadata:
  name: private-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: #Add kubernetes-addons Git URL
  username: #Add yourname-kubernetes-addons
  password: #Add your PAT
type: Opaque
